# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7ecbafb7b6fb72c5d827d66dbe2997cc4054576223df7ed17dc79c38b2bb9f83a4caa5b304d936235e4a8a510566f4bbaa84ef72e2c8887898b75cba31a5eb9

test:
  secret_key_base: a71544d925d2065fdf4cabd6735bbdc9846f1973752e5f4902e3fe217f22340a8372df8233ac9494fee7843e124afe98b6b47deece0b5d21ffcee25c862f1200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
